name: node_shims
version: 0.2.0
# author: Demis Bellot <demis.bellot@gmail.com>
description: Common node and js utils to help in porting of node.js and javascript libs to dart.
homepage: https://github.com/dartist/node_shims/

environment:
  sdk: '>=2.3.0 <=3.0.0'

dev_dependencies:
  test: 
  pedantic:
